# Generated by Django 6.0.6 on 2026-06-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
