# Generated by Django 6.0.6 on 2026-06-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_wallet_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_type',
            field=models.CharField(default='Savings', max_length=50),
        ),
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='wallet',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
